version: "3"
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t public/ public/index.php